In [3]:
import os
import pandas as pd

train_dir = r"C:\Users\abdoe\Downloads\aclImdb\train"
test_dir = r"C:\Users\abdoe\Downloads\aclImdb\test"

def load_reviews_from_folder(folder, label):
    reviews = []
    for filename in os.listdir(folder):
        if filename.endswith(".txt"):
            with open(os.path.join(folder, filename), "r", encoding="utf-8") as f:
                text = f.read()
                reviews.append((text, label))
    return reviews

def load_dataset(base_path):
    pos_reviews = load_reviews_from_folder(os.path.join(base_path, "pos"), 1)
    neg_reviews = load_reviews_from_folder(os.path.join(base_path, "neg"), 0)
    all_reviews = pos_reviews + neg_reviews 
    return pd.DataFrame(all_reviews, columns=["review", "label"])

train_df = load_dataset(train_dir)
test_df = load_dataset(test_dir)

print("Train Shape:", train_df.shape)
print("Test Shape:", test_df.shape)

train_df.to_csv("train_reviews.csv", index=False)
test_df.to_csv("test_reviews.csv", index=False)

Train Shape: (25000, 2)
Test Shape: (25000, 2)

In [5]:
train_df.head()

                                              review  label
0  Bromwell High is a cartoon comedy. It ran at t...      1
1  Homelessness (or Houselessness as George Carli...      1
2  Brilliant over-acting by Lesley Ann Warren. Be...      1
3  This is easily the most underrated film inn th...      1
4  This is not the typical Mel Brooks film. It wa...      1

In [6]:
test_df.head()

                                              review  label
0  I went and saw this movie last night after bei...      1
1  Actor turned director Bill Paxton follows up h...      1
2  As a recreational golfer with some knowledge o...      1
3  I saw this film in a sneak preview, and it is ...      1
4  Bill Paxton has taken the true story of the 19...      1